//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hwoexClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int cat_id { get; set; }
        public int tran_id { get; set; }
        public int acc_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Category Category { get; set; }
        public virtual moneyTransaction moneyTransaction { get; set; }
    }
}
